default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  username: julien
  password: geriboire
  host: localhost
  port: 5433
  database: rocketelevatorsinformationsystem_development
test:
  <<: *default
  adapter: mysql2
  encoding: utf8
  username: julien
  password: geriboire!
  host: localhost
  port: 5433
  database: rocketelevatorsinformationsystem_test

production:
  <<: *default
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: rocketelevatorsinformationsystem_production
  username: julien
  password: geriboire

datawarehouse_development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: datawarehouse_development
  username: julien
  password: geriboire

datawarehouse_test:
  <<: *default
  database: datawarehouse_test

datawarehouse_production:
  <<: *default
  url: <%= ENV['DATAWAREHOUSE_DATABASE_URL'] %>
